import { Injectable } from '@angular/core';
import { USState } from '../models/us-state';

@Injectable()
export class GlobalService {

    getStates(): USState[] {
        return <USState[]>[
            { abbreviation: 'AL', name: 'Alabama' },
            { abbreviation: 'AK', name: 'Alaska' },
            { abbreviation: 'AZ', name: 'Arizona' },
            { abbreviation: 'AR', name: 'Arkansas' },
            { abbreviation: 'CA', name: 'California' },
            { abbreviation: 'CO', name: 'Colorado' },
            { abbreviation: 'CT', name: 'Connecticut' },
            { abbreviation: 'DE', name: 'Delaware' },
            { abbreviation: 'FL', name: 'Florida' },
            { abbreviation: 'GA', name: 'Georgia' },
            { abbreviation: 'HI', name: 'Hawaii' },
            { abbreviation: 'ID', name: 'Idaho' },
            { abbreviation: 'IL', name: 'Illinois' },
            { abbreviation: 'IN', name: 'Indiana' },
            { abbreviation: 'IA', name: 'Iowa' },
            { abbreviation: 'KS', name: 'Kansas' },
            { abbreviation: 'KY', name: 'Kentucky' },
            { abbreviation: 'LA', name: 'Louisiana' },
            { abbreviation: 'ME', name: 'Maine' },
            { abbreviation: 'MD', name: 'Maryland' },
            { abbreviation: 'MA', name: 'Massachusetts' },
            { abbreviation: 'MI', name: 'Michigan' },
            { abbreviation: 'MN', name: 'Minnesota' },
            { abbreviation: 'MS', name: 'Mississippi' },
            { abbreviation: 'MO', name: 'Missouri' },
            { abbreviation: 'MT', name: 'Montana' },
            { abbreviation: 'NE', name: 'Nebraska' },
            { abbreviation: 'NV', name: 'Nevada' },
            { abbreviation: 'NH', name: 'NewHampshire' },
            { abbreviation: 'NJ', name: 'NewJersey' },
            { abbreviation: 'NM', name: 'NewMexico' },
            { abbreviation: 'NY', name: 'NewYork' },
            { abbreviation: 'NC', name: 'NorthCarolina' },
            { abbreviation: 'ND', name: 'NorthDakota' },
            { abbreviation: 'OH', name: 'Ohio' },
            { abbreviation: 'OK', name: 'Oklahoma' },
            { abbreviation: 'OR', name: 'Oregon' },
            { abbreviation: 'PA', name: 'Pennsylvania' },
            { abbreviation: 'RI', name: 'RhodeIsland' },
            { abbreviation: 'SC', name: 'SouthCarolina' },
            { abbreviation: 'SD', name: 'SouthDakota' },
            { abbreviation: 'TN', name: 'Tennessee' },
            { abbreviation: 'TX', name: 'Texas' },
            { abbreviation: 'UT', name: 'Utah' },
            { abbreviation: 'VT', name: 'Vermont' },
            { abbreviation: 'VA', name: 'Virginia' },
            { abbreviation: 'WA', name: 'Washington' },
            { abbreviation: 'WV', name: 'WestVirginia' },
            { abbreviation: 'WI', name: 'Wisconsin' },
            { abbreviation: 'WY', name: 'Wyoming' },
            { abbreviation: 'AS', name: 'AmericanSamoa' },
            { abbreviation: 'DC', name: 'DistrictofColumbia' },
            { abbreviation: 'FM', name: 'FederatedStatesofMicronesia' },
            { abbreviation: 'GU', name: 'Guam' },
            { abbreviation: 'MH', name: 'MarshallIslands' },
            { abbreviation: 'MP', name: 'NorthernMarianaIslands' },
            { abbreviation: 'PW', name: 'Palau' },
            { abbreviation: 'PR', name: 'PuertoRico' },
            { abbreviation: 'VI', name: 'VirginIslands' },
        ];
    }
}

